package tui

import (
	"errors"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/charmbracelet/lipgloss"
	"github.com/muesli/termenv"

	"github.com/martinhg/capiko-ai/internal/agent"
	"github.com/martinhg/capiko-ai/internal/copilot"
	"github.com/martinhg/capiko-ai/internal/sddstatus"
	"github.com/martinhg/capiko-ai/internal/sysinfo"
)

var updateGolden = flag.Bool("update", false, "update golden files")

// TestMain forces a plain ASCII color profile so rendered views are
// deterministic (no ANSI escapes) and golden files stay stable across
// terminals and CI.
func TestMain(m *testing.M) {
	lipgloss.SetColorProfile(termenv.Ascii)
	os.Exit(m.Run())
}

func golden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", name+".golden")
	if *updateGolden {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %q: %v (run: go test ./internal/tui -update)", name, err)
	}
	if got != string(want) {
		t.Errorf("%s view mismatch\n--- got ---\n%s\n--- want ---\n%s", name, got, want)
	}
}

func TestViewGolden(t *testing.T) {
	// Pin the version so release bumps (baseVersion, carried by the
	// x-release-please-version marker) never invalidate the menu/update goldens,
	// which embed the rendered version string. Without this, every release PR
	// fails TestViewGolden until the goldens are regenerated by hand.
	defer func(v string) { Version = v }(Version)
	Version = "0.0.0"

	t.Setenv("COPILOT_CUSTOM_INSTRUCTIONS_DIRS", "") // deterministic golden: home target only
	fixedHost := &copilot.Host{SkillsDir: "/home/user/.copilot/skills"}

	svc := services{host: fixedHost}

	installPicking := newInstall(svc, testCatalog(), map[string]bool{"capiko-hello": true})

	installDone := newInstall(svc, testCatalog(), map[string]bool{}).(*selector)
	installDone.state = selDone
	installDone.result = reconcileResult{
		installed: []string{"capiko-conventions"},
		removed:   []string{"capiko-hello"},
	}

	// A selector with a pending change, viewed through the review gate.
	reviewSel := newInstall(svc, testCatalog(), map[string]bool{"capiko-hello": true}).(*selector)
	reviewSel.desired[0] = false // remove capiko-hello
	reviewSel.desired[1] = true  // install capiko-conventions
	reviewView := newReview(reviewSel)

	sddView := newSDD(svc, testCatalog(), map[string]bool{}, false).(*sddScreen)
	sddView.models["orchestrator"] = "claude-opus-4.8"
	sddView.models["spec"] = "gemini-5.4"

	engramView := newEngram(svc).(*engramScreen)
	engramView.enabled = true
	engramView.server = "https://engram.example.com"
	engramView.vscodeScope = "workspace"

	uninstallEmpty := newUninstall(svc, testCatalog(), map[string]bool{})

	// A fixed report keeps the detection golden deterministic across machines.
	detection := &detectionScreen{
		report: sysinfo.Report{
			OS: "darwin", Arch: "arm64", Shell: "fish", Supported: true,
			Tools: []sysinfo.Tool{
				{Name: "git", Found: true},
				{Name: "curl", Found: true},
				{Name: "brew", Found: true},
				{Name: "node", Found: false},
				{Name: "go", Found: true},
			},
			Dependencies: []sysinfo.Dependency{
				{Name: "copilot", Required: true, Found: true, Version: "1.0.59"},
				{Name: "node", Required: true, Found: false, Install: "brew install node", Auto: true},
				{Name: "npm", Required: true, Found: false, Install: "brew install node", Auto: true},
				{Name: "pnpm", Required: true, Found: false, Install: "brew install pnpm", Auto: true},
				{Name: "git", Required: true, Found: true, Version: "2.43.0"},
				{Name: "curl", Required: true, Found: true, Version: "8.4.0"},
				{Name: "brew", Required: false, Found: true, Version: "4.2.0"},
				{Name: "go", Required: false, Found: false, Install: "see the tool's website to install go"},
			},
			Configs: []sysinfo.Config{
				{Name: "~/.copilot", Exists: true},
				{Name: "~/.copilot/skills", Exists: true},
				{Name: "~/.copilot/instructions", Exists: false},
				{Name: "settings.json", Exists: false},
				{Name: "mcp-config.json", Exists: false},
			},
		},
	}

	cases := []struct {
		name string
		view string
	}{
		{"detecting", App{state: appDetecting}.View()},
		{"notfound", App{state: appNotFound}.View()},
		{"failed", App{state: appFailed, err: errors.New("boom")}.View()},
		{"menu", App{state: appMenu, catalog: testCatalog()}.View()},
		{"menu_update", App{state: appMenu, catalog: testCatalog(), latest: "9.9.9"}.View()},
		{"menu_stale", App{state: appMenu, catalog: testCatalog(), stale: []string{"capiko-hello", "capiko-pr"}}.View()},
		{"menu_advisory", App{state: appMenu, catalog: testCatalog(), advisory: "engram 1.17 recommended"}.View()},
		{"detection", App{state: appScreen, active: detection}.View()},
		{"persona", App{state: appScreen, active: newPersona(svc, testCatalog(), map[string]bool{})}.View()},
		{"install_picking", App{state: appScreen, active: installPicking}.View()},
		{"install_done", App{state: appScreen, active: installDone}.View()},
		{"review", App{state: appScreen, active: reviewView}.View()},
		{"sdd", App{state: appScreen, active: sddView}.View()},
		{"engram", App{state: appScreen, active: engramView}.View()},
		{"headroom", App{state: appScreen, active: &headroomScreen{svc: svc, detected: false}}.View()},
		{"instructions", App{state: appScreen, active: newInstructions(svc)}.View()},
		{"uninstall_empty", App{state: appScreen, active: uninstallEmpty}.View()},
		{"sync_confirm", App{state: appScreen, active: newSync(svc, testCatalog(), nil)}.View()},
		{"sync_done_agents", App{state: appScreen, active: &syncScreen{
			catalog:      testCatalog(),
			agentCatalog: []agent.Agent{{Name: "capiko-sdd-explore"}, {Name: "capiko-sdd-apply"}},
			state:        syncDone,
			count:        5,
			skillNames:   []string{"capiko-hello", "capiko-conventions", "capiko-pr"},
			agentNames:   []string{"capiko-sdd-explore", "capiko-sdd-apply"},
		}}.View()},
		{"backups_empty", App{state: appScreen, active: newBackups(svc)}.View()},
		{"sdd_status_list", App{state: appScreen, active: &sddStatusScreen{entries: []sddChange{
			sddChangeFixture("add-auth", "apply", sddstatus.Dependencies{
				Proposal: sddstatus.DependencyAllDone, Specs: sddstatus.DependencyAllDone,
				Design: sddstatus.DependencyAllDone, Tasks: sddstatus.DependencyAllDone,
				Apply: sddstatus.DependencyReady,
			}, 2, 5),
			sddChangeFixture("rework-tui", "spec", sddstatus.Dependencies{
				Proposal: sddstatus.DependencyAllDone, Specs: sddstatus.DependencyReady,
				Design: sddstatus.DependencyReady,
			}, 0, 0),
		}}}.View()},
		{"sdd_status_detail", App{state: appScreen, active: &sddStatusScreen{detail: true, entries: []sddChange{
			sddChangeFixture("add-auth", "apply", sddstatus.Dependencies{
				Proposal: sddstatus.DependencyAllDone, Specs: sddstatus.DependencyAllDone,
				Design: sddstatus.DependencyAllDone, Tasks: sddstatus.DependencyAllDone,
				Apply: sddstatus.DependencyReady,
			}, 2, 5),
		}}}.View()},
		{"update_prompt", App{state: appUpdatePrompt, latest: "9.9.9", cursor: promptDefaultCursor}.View()},
		{"soon", App{state: appScreen, active: newSoon("Upgrade tools")}.View()},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			golden(t, tc.name, tc.view)
		})
	}
}
