package skillregistry

import (
	"fmt"
	"strings"
)

// contract is the delegator-use-only preamble, mirrored from the registry
// capiko dogfoods. It tells an orchestrator how to use the index: pass exact
// paths, never generated summaries, so sub-agents load the full SKILL.md.
const contract = "**Delegator use only.** This registry is an index, not a summary. " +
	"Any agent that launches sub-agents reads it to select relevant skills by trigger, " +
	"then passes the exact `SKILL.md` paths for the sub-agent to read before work. " +
	"`SKILL.md` stays the source of truth — do not inject generated summaries; pass paths so the sub-agent loads the full runtime contract."

// RenderMarkdown renders the registry as the human- and agent-readable index:
// the scanned sources, the delegator contract, and a table of skills by
// trigger/path. The table header is always present, even with no rows.
func RenderMarkdown(reg Registry) string {
	lines := []string{
		fmt.Sprintf("# Skill Registry — %s", reg.Project),
		"",
		"<!-- Generated by `capiko-ai skill-registry`. Re-run to regenerate. -->",
		"",
		"## Sources scanned",
		"",
	}
	for _, s := range reg.Sources {
		lines = append(lines, fmt.Sprintf("- %s", s))
	}
	lines = append(lines,
		"",
		"## Contract",
		"",
		contract,
		"",
		"## Skills",
		"",
		"| Skill | Trigger / description | Scope | Path |",
		"| --- | --- | --- | --- |",
	)
	for _, e := range reg.Entries {
		lines = append(lines, fmt.Sprintf("| `%s` | %s | %s | `%s` |",
			e.Name, cell(e.Description), e.Scope, e.Path))
	}
	return strings.Join(lines, "\n") + "\n"
}

// cell keeps a description from breaking the markdown table: literal pipes are
// escaped and any newline is flattened to a space.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.ReplaceAll(s, "|", "\\|")
}
